name: gitActions

on:
  pull_request:
  push:
    branches:
      - new-githubActions
      - main
      - ft-the-hell-is-here
      
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
  unit-tests:
    runs-on: ubuntu-latest
    env:
      PORT: ${{secrets.PORT}}
      HOST: ${{secrets.HOST}}
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      MONGODB_URL_TEST: ${{secrets.MONGODB_URL_TEST}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
    strategy:
      matrix:
        node-version: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run test   
  test:
    name: run-unit test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: test
      run: npm run test
  
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Deploy
      run: npm start